all:
	gcc -o ipow ipow.c ipow.h main_ipow.c
2:
	gcc -o ipow1 ipow.s main_ipow.c
111:
	gcc -o ipow2 ipow1.s main_ipow.c
test:
	gcc -o test test.s main_ipow.c
3:
	gcc -o test1 test1.s main.c
4:
	gcc -o test2 digit_freq.h digit_freq.c main.c
5:
	gcc -o test3 digit_freq.s main.c
6:
	gcc -o test4 shi.s main.c
8:
	gcc -o ipow5 ipow3.s main_ipow.c
