
all:
	cp ../../exam1_8/parts.h .
	cp ../../exam1_8/main.c .
	cp ../../exam1_8/makefile .
	gcc -g -o q8 main.c parts.c
	make git

git:
	git add parts.h
	git add main.c
	cp  ../../exam1_8/makefile .
	git add makefile
	git commit -m "harcourt test files"
	git push

